version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
    environment:
      SA_PASSWORD: "Password."
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes: 
      - db_data:/var/opt/mssql
volumes:
  db_data: